language: node_js
node_js:
  - "lts/*"
before_script:
  - chmod a+x ./deploy.sh
script:
  - npm test
  - npm run build
after_success: npm run coveralls
cache: npm
deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true
    on:
      branch: master